apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sample-node-app
  name: sample-node-app 
spec:
  ports:
  - name: http
    port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    app: sample-node-app
  type: NodePort
status:
  loadBalancer: {}